version: '3.7'

services:
 angular:
  build: angular-app # specify the directory of the Dockerfile
  ports:
  - "4200:4200" # specify port forewarding
  
 express: #name of the second service
  build: express-server # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports forewarding
  links:
  - database # link this service to the database service

 database: # Nom du 2eme service
  image: mongo 
  ports:
  - "27017:27017" 